name: master deploy

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: commit
        env:
          KEY: ${{ secrets.TDY_PRIVATE_KEY }}
          HOST: ${{ secrets.TDY_HOST }}
        run: |
          echo "添加key"
          mkdir -p ~/.ssh/ && echo "$KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          echo "启动ssh-agent"
          eval "$(ssh-agent -s)"
          echo "添加秘钥"
          ssh-add ~/.ssh/id_rsa
          echo "地址写入known_hosts，防止警告"
          ssh-keyscan -t rsa $HOST >> ~/.ssh/known_hosts
          echo "同步文件"
          scp -o StrictHostKeyChecking=no -r ./welfare-lottery-scrapy root@${HOST}:/var/mt-scrapy/
          echo "上传完成,开始重启"
          ssh -o StrictHostKeyChecking=no root@${HOST} "/var/mt-scrapy/welfare-lottery-scrapy/reset.sh"
          echo "重启完成"
        # echo "获取进程号"
        # PID=$(ssh -o StrictHostKeyChecking=no root@${HOST} "ps -ef | grep wl_apscheduler.py | grep -v grep | awk '{print \$2}'")
        # echo PID
        # echo "关闭老进程"
        # ssh -o StrictHostKeyChecking=no root@${HOST} "kill -9 ${PID}"
        # echo "启动新进程"
        # ssh -o StrictHostKeyChecking=no root@${HOST} "cd /var/mt-project/mt-scrapy/welfare-lottery-scrapy/ && nohup python3 ./wl_apscheduler.py >output.log 2>& 1 &"
        # echo "完成部署"
        # ssh -o StrictHostKeyChecking=no root@${HOST} "ps -ef | grep wl_apscheduler.py | grep -v grep | awk '{print \$2}' | xargs kill -9"
        # ssh -o StrictHostKeyChecking=no root@${HOST} "cd /var/mt-project/mt-scrapy/welfare-lottery-scrapy/; ps -ef | grep wl_apscheduler.py | grep -v grep | awk '{print $2}' | xargs kill -9; nohup python3 ./wl_apscheduler.py &;"
        # echo "重启服务器"
        # ssh -o StrictHostKeyChecking=no root@${HOST} "sudo /usr/sbin/nginx -s reload"
        # 后端服务相关
        # scp -o StrictHostKeyChecking=no -r server/crmserver ubuntu@${HOST}:/home/ubuntu/
        # ssh -o StrictHostKeyChecking=no ubuntu@${HOST} "sudo /home/ubuntu/crmapi/restart.sh > /dev/null 2>&1 &"

        # echo "配置config"
        # echo "Host tdypro\nHostName ${HOST}\nPort 22\nUser root\nIdentityFile ~/.ssh/id_rsa" > ~/.ssh/config
        # cat ~/.ssh/config
